/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from '@trpc/server';
import { z } from 'zod';

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { postSchema, createPostSchema } from '@repo/contracts/posts';

const appRouter = t.router({
  posts: t.router({
    findAll: publicProcedure
      .output(z.array(postSchema))
      .query(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
    create: publicProcedure
      .input(createPostSchema)
      .output(postSchema)
      .mutation(async () => 'PLACEHOLDER_DO_NOT_REMOVE' as any),
  }),
});

export type AppRouter = typeof appRouter;
