/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { userIdSchema, getFollowersSchema, paginatedUserPreviewsSchema, getFollowingSchema, userPreviewSchema, updateProfileSchema, userProfileSchema } from "@repo/contracts/users";
import { createCommentSchema, getCommentsSchema, paginatedCommentsSchema, deleteCommentSchema } from "@repo/contracts/comments";
import { findAllPostsSchema, paginatedPostsSchema, findByIdPostSchema, postSchema, createPostSchema, likePostSchema } from "@repo/contracts/posts";
import { nullableStoryGroupSchema, getUserStoriesSchema, getFeedStoriesSchema, paginatedStoryGroupsSchema, createStorySchema, storySchema } from "@repo/contracts/stories";

const appRouter = t.router({
  users: t.router({
    follow: publicProcedure
      .input(userIdSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    unfollow: publicProcedure
      .input(userIdSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getFollowers: publicProcedure
      .input(getFollowersSchema)
      .output(paginatedUserPreviewsSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getFollowing: publicProcedure
      .input(getFollowingSchema)
      .output(paginatedUserPreviewsSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getSuggestedUsers: publicProcedure
      .output(z.array(userPreviewSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    updateProfile: publicProcedure
      .input(updateProfileSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getUserProfile: publicProcedure
      .input(userIdSchema)
      .output(userProfileSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  comments: t.router({
    create: publicProcedure
      .input(createCommentSchema)
      .output(z.object({ id: z.number() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findByPostId: publicProcedure
      .input(getCommentsSchema)
      .output(paginatedCommentsSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure
      .input(deleteCommentSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  posts: t.router({
    findAll: publicProcedure
      .input(findAllPostsSchema)
      .output(paginatedPostsSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findById: publicProcedure
      .input(findByIdPostSchema)
      .output(postSchema.nullable())
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(createPostSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    likePost: publicProcedure
      .input(likePostSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  stories: t.router({
    getOwnStories: publicProcedure
      .output(nullableStoryGroupSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getUserStories: publicProcedure
      .input(getUserStoriesSchema)
      .output(nullableStoryGroupSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getFeedStories: publicProcedure
      .input(getFeedStoriesSchema)
      .output(paginatedStoryGroupsSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(createStorySchema)
      .output(storySchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
